### ISSUE TITLE
async_forward_entry_setup deprecation

### ISSUE THREAD

**Issue by nuker1991** [gvigroux/hon#148]
i get a deprecation message, can someone solve this before 2025 ?

`2024-08-09 11:13:43.315 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration hon with title: xxx@xxx.xxx and entry_id: xxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.`

**Comment by gvigroux** [comment]
Thanks, I will look into it

**Comment by gvigroux** [comment]
I already fixed it 2 months ago :)

**Comment by dbdavid44** [comment]
@gvigroux I still have this issue personally and I'm using the latest version freshly installed.

I just moved away from the original fork from Andre0512/hon cause bugs are stacking up and yours seems more functional.

Anyway here is the error with version 0.7.4:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 4:31:43 PM (4 occurrences)
Last logged: 4:31:45 PM

Detected code that calls async_forward_entry_setup for integration hon with title: xxx@x.com and entry_id: 01J73VNYQGE3FPA2xxxxxxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
```
