### ISSUE TITLE
After update to the last version on git Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by tukker01** [gvigroux/hon#45]
I reinstalled the app, no result same error when i want to add the itergration hon 
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by shaft23** [comment]
Same problem here

**Comment by bakker284** [comment]
Same here

**Comment by arjanvanleent** [comment]
Same here

**Comment by danielriosantos** [comment]
Hi, I'm having the same issue.
This error comes up in logs:

Logger: homeassistant.config_entries
Source: config_entries.py:849
First occurred: 23:20:42 (1 occurrences)
Last logged: 23:20:42

Error occurred loading configuration flow for integration hon: Exception importing custom_components.hon.config_flow

Thanks and keep up the hard work!

**Comment by gvigroux** [comment]
I just fixed it :) 
sorry, wrong merge!

**Comment by Jaykurb** [comment]
I'm still getting;

Config flow could not be loaded: {"message":"Invalid handler specified"}

After update. Unable to add integration. Is there something I'm missing?

**Comment by bakker284** [comment]
Al fix here, no errors and airconditioning working perfect again
